"""add_context_unique_constraint

Revision ID: 7a34c12ceaec
Revises: fd806ff82074
Create Date: 2026-06-09 12:41:44.719941

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7a34c12ceaec'
down_revision: str | None = 'fd806ff82074'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_context_tenant_ns_key', 'context_entries', ['tenant_id', 'namespace', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_context_tenant_ns_key', 'context_entries', type_='unique')
    # ### end Alembic commands ###
