"""add_memory_deleted_at

Revision ID: fd806ff82074
Revises: 9d4cc5745e91
Create Date: 2026-06-09 11:33:07.761922

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fd806ff82074'
down_revision: str | None = '9d4cc5745e91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'deleted_at')
    # ### end Alembic commands ###
